name: Create Bookmark
on:
  workflow_dispatch:
    inputs:
      bookmark_url:
        description: 'URL'
        required: true
        type: string
      bookmark_title:
        description: 'Title'
        required: false
        type: string
      bookmark_tags:
        description: 'Tags'
        required: false
        type: string
      bookmark_notes:
        description: 'Notes'
        required: false
        type: string
jobs:
  create_bookmark:
    name: Create a new Bookmark
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Bookmark Details
        run: |
          echo "- Bookmark URL: ${{ github.event.inputs.bookmark_url }}" >> $GITHUB_STEP_SUMMARY
          echo "- Bookmark Title: ${{ github.event.inputs.bookmark_title }}" >> $GITHUB_STEP_SUMMARY
          echo "- Bookmark Tags: ${{ github.event.inputs.bookmark_tags }}" >> $GITHUB_STEP_SUMMARY
          echo "- Bookmark Notes: ${{ github.event.inputs.bookmark_notes }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Create bookmark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BOOKMARK_URL: ${{ github.event.inputs.bookmark_url }}
          BOOKMARK_TITLE: ${{ github.event.inputs.bookmark_title }}
          BOOKMARK_TAGS: ${{ github.event.inputs.bookmark_tags }}
          BOOKMARK_NOTES: ${{ github.event.inputs.bookmark_notes }}
        run: | 
          bundle exec script/bookmark.rb --commit="${GITHUB_REPOSITORY}#${GITHUB_REF##*/}" >> $GITHUB_STEP_SUMMARY
